disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - nesting
  - force_cast
  - large_tuple
  - redundant_string_enum_value
  - non_optional_string_data_conversion
  - for_where
  - implicit_optional_initialization

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - first_where
  - last_where
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - toggle_bool
  - unneeded_parentheses_in_closure_argument

excluded:
  - .build
  - DerivedData
  - Pods
  - Carthage
  - Package.swift

reporter: xcode
